### PR TITLE
Feature/WebdriverIO-Setup

### PR DESCRIPTION
**Pull request by we-abhijeet-g001**
PR Details:

1. This documentation is regarding the setup process of the WebdriverIO.
2. All the steps and processes are added with images and descriptions.
3. Added all the appropriate links for the setup process.
4. Sections Added:
     - Requirements
     - Setup WebDriverIO Project
     - Configuration
     - Running the test script
     - Mocha Framework
5. Documentation video: [WebdriverIO Setup](https://drive.google.com/file/d/1EyldiEHIaJL6P5xz8Aa-baITdaizzx9X/view?usp=sharing)

### CODE REVIEW

**Comment by themodernpk** [comment]
@we-abhijeet-g001 this tutorial should be with `appium`, this can be common for both web and mobile. There are multiple packages that you missed that can be installed during the setup process.

**Comment by we-abhijeet-g001** [comment]
> @we-abhijeet-g001 this tutorial should be with `appium`, this can be common for both web and mobile. There are multiple packages that you missed that can be installed during the setup process.

Sir, we thought there should be another separate setup documentation for `appium` setup from scratch. But I can modify this to add `appium`. Should I modify this to have `appium` or a separate setup for appium would be there?

**Comment by themodernpk** [comment]
@we-abhijeet-g001 we will use `appium` as default in all projects

**Comment by we-abhijeet-g001** [comment]
> @we-abhijeet-g001 we will use `appium` as default in all projects

Ok Sir, I will change the setup to add appium in it. Will give you an update once it is completed.

**Pull request merged**
